Dockerfile
requirements.txt

@yostashiro 
Tested w/ https://hub.docker.com/r/timlai/odoo-docker/builds/bseqe8akbooza2pfy37x6r9/

[IMP] Set environment variable and add odoorpc

---

Dockerfile

Task [771](https://www.quartile.co/web#id=938&action=771&model=project.task&view_type=form&menu_id=505)

[10.0][T771]- Docker Build of Odoo

---

Dockerfile

Task [771](https://www.quartile.co/web#id=938&action=771&model=project.task&view_type=form&menu_id=505)

[11.0][T771]- Docker Build of Odoo

---

requirements.txt

Task [1225](https://www.quartile.co/web?debug#id=1225&action=771&model=project.task&view_type=form&menu_id=505)
Reflect the latest requirements.txt from
https://github.com/odoo/odoo/blob/75add3d1496ee64d5278bc4250ac41dc4349d460/requirements.txt

[1225][13.0][IMP] requirements.txt

---

requirements.txt

Task [1225](https://www.quartile.co/web?debug#id=1225&action=771&model=project.task&view_type=form&menu_id=505)
Reflect the latest requirements.txt from
https://github.com/odoo/odoo/blob/72252ff8a6aaae86fae121a7006039a40ba6efe2/requirements.txt

[1225][12.0][IMP] requirements.txt

---

requirements.txt

Task [1225](https://www.quartile.co/web?debug#id=1225&action=771&model=project.task&view_type=form&menu_id=505)
Reflect the latest requirements.txt from
https://github.com/odoo/odoo/blob/b01aac41a670988b2d85f2a280bdb5841d483f63/requirements.txt

[1225][11.0][IMP] requirements.txt

---

Dockerfile

[1508](https://www.quartile.co/web?debug=#id=1508&action=771&model=project.task&view_type=form&menu_id=505)

[1508][IMP] Switch to ocb

---

Dockerfile
entrypoint.sh

[1329][IMP] Revert os version to ubuntu

---

Dockerfile

[1627](https://www.quartile.co/web#id=1627&model=project.task&view_type=form&menu_id=)

[1627][FIX] Update ubuntu to 18.04

---

Dockerfile

[1627](https://www.quartile.co/web#id=1627&model=project.task&view_type=form&menu_id=)
Ref: https://stackoverflow.com/questions/65869296/installing-pip-is-not-working-in-bitbucket-ci/65871131#65871131

[1627][FIX] Specify pip version

---

Dockerfile

[1627](https://www.quartile.co/web#id=1627&model=project.task&view_type=form&menu_id=)

[1627][IMP] Update ubuntu version

---

Dockerfile
entrypoint.sh

This reverts commit 44a49667e70146ee04fda921e38af45ffcef836f.

Revert "[1329][IMP] Revert os version to ubuntu (#40)"

---

Dockerfile
README.md

[2032](https://www.quartile.co/web?debug=1#id=2032&action=771&model=project.task&view_type=form&menu_id=505)

[2032][IMP] Update Dockerfile, README for 15.0

---

Dockerfile

[2417](https://www.quartile.co/web?debug=1#id=2417&action=771&active_id=2358&model=project.task&view_type=form&menu_id=505)

15.0 [2417][IMP] remove odoo from image

---

entrypoint.sh

[2417])(https://www.quartile.co/web?debug=1#id=2417&action=771&active_id=2358&model=project.task&view_type=form&menu_id=505)

15.0 [2417][FIX] entrypoint.sh: odoo directory

---

Dockerfile

[2417](https://www.quartile.co/web?debug=1#id=2417&action=771&active_id=2358&model=project.task&view_type=form&menu_id=505)

12.0 [2417][FIX] Dockerfile:python

---

Dockerfile

[2417](https://www.quartile.co/web?debug=1#id=2417&action=771&active_id=2358&model=project.task&view_type=form&menu_id=505)
Remove odoo from image
Change the ODOO_SOURCE =OCA/OCB

14.0 [IMP] remove odoo from image

---

entrypoint.sh

[2417](https://www.quartile.co/web?debug=1#id=2417&action=771&active_id=2358&model=project.task&view_type=form&menu_id=505)
Change the odoo directory

14.0 [2417][FIX] enterypoint.sh: odoo directory

---

Dockerfile

[2903](https://www.quartile.co/web?#id=2903&action=771&model=project.task&view_type=form&menu_id=505)

13.0 [2903][FIX] Dockerfile: point to the correct distribution for postgresql

---

Dockerfile

[2903](https://www.quartile.co/web?#id=2903&action=771&model=project.task&view_type=form&menu_id=505)

10.0 [2903][FIX] Dockerfile: point to the correct distribution for postgresql

---

Dockerfile

[2903](https://www.quartile.co/web?#id=2903&action=771&model=project.task&view_type=form&menu_id=505)

11.0 [2903][FIX] Dockerfile: point to the correct distribution for postgresql

---

Dockerfile

Build dockerfile in local environment and working fine.

[13.0][2417][FIX] remove requirement.txt : get directly from odoo source

---

Dockerfile
README.md

[3991](https://www.quartile.co/web#id=3991&cids=3&model=project.task&view_type=form)
[4013](https://www.quartile.co/web#id=4013&cids=3&model=project.task&view_type=form)

[17.0][3991][IMP] update dockerfiles, README

---

Dockerfile

[4013](https://www.quartile.co/web#id=4013&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

[4013][17.0][FIX] Change version wkhtmltopdf 0.13 to 0.12.6.1 to avoid printig problems

---

Dockerfile

[4013](https://www.quartile.co/web#id=4013&cids=3&model=project.task&view_type=form)

[16.0][4013][IMP]Switch wkhtmltopdf repo to Odoo

---

Dockerfile

[4552](https://www.quartile.co/web#cids=3&menu_id=505&action=1457&model=project.task&view_type=form&id=4552)
Related: https://www.postgresql.org/message-id/ZN4OigxPJA236qlg%40msg.df7cb.de

[10.0][4552][FIX] Dockerfile: update postgresql repo

---

Dockerfile

[4552](https://www.quartile.co/web#id=4552&menu_id=505&cids=3&action=1457&model=project.task&view_type=form0)
Reference: https://github.com/Tecnativa/doodba/pull/636

[4552][17.0][FIX] dockerfile: use gevent 22.10.2
